apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h9x0r29nr-java-quarkus
  janus-idp.io/tekton: h9x0r29nr-java-quarkus
  backstage.io/kubernetes-id: h9x0r29nr-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h9x0r29nr-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
