apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h9x0r29nr-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-95c066174c.r2db.p3.openshiftapps.com/rhtap/rhtap-qe:6b783383d5b474cc2c4345cb1bc7bcc1f43f17c1@sha256:9185b621c0454d0a0f68febba4a63c8243b81d2b4d52db1e878dbdfb58e3c9e5
          name: container-image
